### ISSUE TITLE
customData.save fails when removing last key

### ISSUE THREAD

**Issue by tuck182** [stormpath/stormpath-sdk-node#177] opened 2015-08-17 21:37 UTC
We're seeing error where, when removing a key from customData and saving:

```
      req.user.customData.remove('key-to-remove');
      req.user.customData.save(function (err) {
        if (err) {
          return next(err);
        }
        . . . do stuff . . .
      });
```

if the key being removed is the LAST key in the customData object, we get the following error:

```
21:33:01.139Z ERROR main: HTTP 400, Stormpath 2000 (http://docs.stormpath.com/errors/2000): CustomData properties cannot be null, empty, or blank. (err.code=2000)
```

This is fairly easy to test by creating a user with a single key/value in customData, then using remove/save to remove it.

Given that the customData object can be empty, it should be possible to remove the last key and have it result in being empty. It seems like it might be possible to check whether there are no keys remaining and then use `customData.remove` instead, but a) there doesn't seem to be a good way to do this and b) it doesn't really feel like this sort of check should be necessary.

**Comment by rdegges** [comment] 2015-09-01 06:28
Hmm.

This is a tricky one. I've been debugging this for the past hour and a half.

Here's what I know:

- I can create customData with a single field using the raw rest API via curl.
- I can delete my last customData field using the raw rest API via curl.
- I can verify that the request we're generating with node is trying to DELETE the right URL, but it is failing.

I'm not sure why the failure is occurring yet. I'll need to dig into this more tomorrow.

**Comment by tuck182** [comment] 2015-09-01 06:30
Well I'm glad I was able to find something interesting, I guess.  :)

Thanks for looking into it!

**Comment by rdegges** [comment] 2015-09-01 06:33
Oh, actually. I was about to go to sleep, and it just occured to me why this is failing... One sec...

**Comment by rdegges** [comment] 2015-09-01 06:54
So -- the issue is that we're ONLY doing the delete operation when the developer calls .save(). This means that after removing the last key, we then attempt to save() an empty body to customdata, which isn't valid -- hence the error.

I need to find a way to cancel the save() bit if we've removed everything -- a bit easier said than done =)

**Comment by rdegges** [comment] 2015-09-01 16:52
Just got a working patch for this + tests. I'm going to resolve it and cut a release today.

**Comment by tuck182** [comment] 2015-09-01 16:52
Awesome, thanks for the quick follow-up!

**Comment by rdegges** [comment] 2015-09-01 18:30
Grr, ran into some issues with the async library that are preventing me from releasing this right now. I'm still working on it, but might get this out this afternoon instead of this morning :(

**Comment by rdegges** [comment] 2015-09-01 18:46
Running the final tests on this now to double check and make sure everything is good to go.

**Comment by rdegges** [comment] 2015-09-01 19:04
Ok! This is all working and tested =)

Going to cut a release right now. I'll update here once it is out.

**Comment by rdegges** [comment] 2015-09-01 19:13
Ok! 0.11.2 was just published to npm. Let me know if you have any issues =) Closing this out.

**Closed by rdegges** 2015-09-01 19:13 UTC
Labels: bug
